### ISSUE TITLE
Add "sort by" to preferences so users can save their preferred "sort by" default

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#198]

**Comment by ellesmith88** [comment]
@rsmith013 Quite stuck on this! My work is on branch `issue/198/add_sort_by` - can't get the submit to work and I'm also confused about how you did it so that the preferred facets are then applied to the 'home' screen. 

I was wondering if you could have a look or if not I can just do 2 separate views/forms?

**Comment by rsmith013** [comment]
customfield_13569
