### ISSUE TITLE
Are all grants migrated properly?

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#200]
It has been pointed out that there are far more unassigned grants than in the live system. 
This could be:
-  because we are using old data from share point to add in the assigned datacentre 
- grants have been cleared out of datamad (sharepoint) but we still have them from siebel

Just putting this here so we understand where this difference comes from.

**Comment by ellesmith88** [comment]
This is also causes an issue with the date added field as we update this from the Sharepoint csv. So any grants that don't exist in sharepoint have their 'date added' as whenever they were added to the database (which could be years after the actual start date of the grant).

Agreed that it is because we are updating these fields from sharepoint. So some of the grants from siebel no longer exist in sharepoint and aren't updated.

**Comment by rsmith013** [comment]
This is solved now we are in production. I think the issue was related to point 2 in the original post.
