### ISSUE TITLE
Wrong date for DMP agreed

### ISSUE THREAD

**Issue by rsmith013** [cedadev/datamad2#404]
We’ve just agreed a DMP with a grant, and updated the info on DataMad for the grant to indicate that the DMP has been agreed, but instead of displaying today’s date, it’s displaying the 4th November 2020 and showing the CFS document. The grant in question is NE/T007478/1.

**Comment by ellesmith88** [comment]
@rsmith013 Currently the date for dmp agreed, if there is a document, is the date the document was uploaded rather than the date the box was ticked. Is there a reason for this behaviour? 

From the above email it sounds like it might be better to use the date the box was ticked even when there is a document.

**Comment by rsmith013** [comment]
@ellesmith88 that would be my expected behaviour. Only show a date, if the box has been ticked and display the date that happened. 

dmp_agreed_date is a MonitorField 
`dmp_agreed_date = MonitorField(monitor='dmp_agreed', when=[True])`
It should only populate when `dmp_agreed == True`
