### ISSUE TITLE
Larger documents have to be saved in a different way to upload them

### ISSUE THREAD

**Issue by ellesmith88** [cedadev/datamad2#419]
Original comment for the the system could be improved:

> Allowing the upload of larger documents without having to save them in a different way

I asked:

- What is the error when you try and upload a file that is too large?
- Do you get this when bulk uploading documents or for individual uploads or both?
- Do you have an idea of the size of file that is too large to be uploaded normally?
- What do you mean by saving them in a different way – is this a workaround you are using to upload your larger documents?
- Any other details/ examples you think might be relevant.

Response:

> It’s not a big deal really, but we were told when there’s an issue uploading, it could be because of the file size (above 2 MB) and to try reducing the file size before uploading:
 

> Open pdf and save.
> Open Adobe, open relevant file
> Select File > Save As Other > Reduced Size PDF > Make compatible with: Acrobat 7.0 and later > OK
>  
> When we do that, it saves OK.  We don’t tend to do bulk uploading.

**Comment by rsmith013** [comment]
Try uploading a document larger than 2MB to the single file upload to trace the issue.

**Comment by Mahir-Sparkess** [comment]
There is no issue with uploading large files (tested on 1.07GB doc) however can not uploaded more than 1 supporting doc to one grant.  i.e. Considers NE_P00573X_1_CFS.pdf and NE_P00573X_1_DMP.pdf to be the same and gives error '<file2> has already been uploaded' even if <file1> is different to <file2>

Issue change to let one grant have many documents?

**Comment by rsmith013** [comment]
this is intentional. It would be a mistake to upload the same file to a grant with the same content, even if it has different names. Guards duplication and un-intentional duplication.

Determining whether a file has already been uploaded is based on a hash of the file so tests the contents.
https://github.com/cedadev/datamad2/blob/780c167b855f6b41f3f06565b0b64633e48c835e/datamad2/models/document_store.py#L49
https://github.com/cedadev/datamad2/blob/780c167b855f6b41f3f06565b0b64633e48c835e/datamad2/models/document_store.py#L23

**Comment by rsmith013** [comment]
tried on live server with 10MB file and it was fine. Need to ask user for more info.

**Comment by ellesmith88** [comment]
Update from user: everything is fine now and file size doesn't seem to be an issue
